### ISSUE TITLE
Do not add datagen related things if they are not needed

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/OperaPublicaCreator#2]

**Comment by OrionDevelopment** [comment]
This is the ldtteams standard Minecraft forge, setup. I don't see a reason why we should disable the datagen options....

**Comment by Nightenom** [comment]
Projects without datagens still do get datagen folders and runs added, while it's not as annoying as run folders name, it's still unnecessary.

**Comment by OrionDevelopment** [comment]
Which project does not have datagen except blockui.

**Comment by Raycoms** [comment]
I think Structurize doesn't have it anymore either now.

**Comment by OrionDevelopment** [comment]
Hmm. it won't be on my high priority list. But when I touch it again i will see what I can do
