### ISSUE TITLE
Automatically declare curse dependencies

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/OperaPublicaCreator#3]
https://github.com/matthewprenger/CurseGradle/wiki

On curse you can set "required library etc". Would be good to detect this automatically and tell curse about it.
I believe we need to define the curseid of the dependencies somewhere.

**Comment by OrionDevelopment** [comment]
You can now specify both optional and required dependencies in curse with OPC.
Use the fields:
- `requiredCurseDependencies`
- `optionalCurseDependencies`
as `;`-seperated lists of curse ids to specify the dependencies during the upload.
